name: Generate Snake Animation

on:
  schedule: # otomatis update setiap 12 jam
    - cron: "0 */12 * * *"
  workflow_dispatch: # bisa dijalankan manual dari tab Actions
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # ✅ fix: kasih izin write ke repo
      contents: write
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: raihanrama
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
